### ISSUE TITLE
Attribute error in tasks.MultiModelFit and name error in utils

### ISSUE THREAD

**Issue by vibha15** [CiaranWelsh/pycotools3#2]
Hi,
I am trying to perform model selection using tasks.MultiModelFit, but it shows the Attribute error saying "AttributeError: module 'pycotools3.tasks' has no attribute 'MultiModelFit' ". 

Also while running time course, it reflects name error. I am attaching here the screen shot for you to take a look. 

I am working with pycotools 3 and COPASI 4.24. Thanks for your time.

Vibha
I 
<img width="1280" alt="Attribute and name error" src="https://user-images.githubusercontent.com/52018214/61164985-565bd800-a4e0-11e9-80f1-60d079a0beae.png">

**Comment by CiaranWelsh** [comment]
Hi Vibha, 

I think you might be looking at the documentation for pycotools and using pycotools3. They are actually different packages. One of the big differences between them is the way parameter estimations are handled for multiple models. Please take a look at [this](https://pycotools3.readthedocs.io/en/latest/Examples/parameter_estimation_multiple_models.html) example. Notice that instead of a `model.Model` instance, a list of `model.Model` instances are passed to the `ParameterEstimation.Context`. Then, run your parameter estimations for however many models you have and compare the objective function value. You could also calculate the [AIC](http://www.turkupetcentre.net/petanalysis/model_aic.html) (use the corrected version if you can) from the RSS

**Comment by vibha15** [comment]
Hi Mr Welsh,
Thank you so much for your explanation.
Yes, I looked in the pycotools documentation. Actually, i am more interested in violin plot presentation of errors.
But, it does not work in pycotools3 as i observed.

Anyways, i did the parameter estimation with multiple models and obtained the RSS. Proceeding towards AIC.
Thanks for your time.


Vibha

________________________________

**Comment by CiaranWelsh** [comment]
Ah I see. Apologies for not building this feature into Pycotools3 yet. Its only me maintaining the code and I've been busy with other things. The best way to do this is by taking the data that you get from `viz.Parse().data` and calculating the [AICc](https://stats.stackexchange.com/questions/69723/two-different-formulas-for-aicc) directly from the RSS using the formula. Its a simple calculation. For violin plots, they are actually also very easy to plot using seaborn. I'd recommend having a [look](https://seaborn.pydata.org/generated/seaborn.violinplot.html). Good luck.

**Comment by vibha15** [comment]
No problem. You are fine.

I am following the AIC and seaborn violin plot pages what you have directed. Hopefully, i could perform those nicely.

Thank you so much for your time and detailed explanation for pycotools.

Vibha
________________________________
